{ config, pkgs, lib, ... }:
  # This file was initially generated by nixos-generate-config.
  # After initial setup, customize as needed.

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];

  # boot.kernelModules = [ "kvm-intel" ]; # TODO: Conflicting with AMD microcode. Let nixos-generate-config determine this.

  # Filesystems - update these based on your actual setup
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/YOUR-ROOT-UUID";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/YOUR-BOOT-UUID";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/YOUR-SWAP-UUID"; }
  ];

  # CPU Microcode
  hardware.cpu.amd.updateMicrocode = true;

  # NVIDIA GPU (RTX 2070 SUPER)
  # Handled by modules/hardware/nvidia.nix
}
