# Main system configuration for the "nixos" host.
#
# This file defines host-specific settings and ties all modules together.
# The hardware-configuration.nix next to this file is auto-generated by the
# NixOS installer — it knows your disk layout, CPU, kernel modules, and
# filesystems. DO NOT edit it manually.
#
# To apply changes after editing any file in this repo:
#   sudo nixos-rebuild switch --flake /etc/nixos#nixos
#
# Shorter alias (defined in home/radu.nix):
#   rebuild

{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix    # Auto-generated — do not edit

    ../../modules/common.nix        # Locale, timezone, fonts, audio
    ../../modules/desktop.nix       # Niri + KDE, display manager, Wayland tools
    ../../modules/development.nix   # Compilers, debuggers, build tools
    ../../modules/gaming.nix        # Steam, Lutris, GameMode, RetroArch
    ../../modules/vm.nix            # QEMU/KVM guest tools (SPICE + qemu-agent)
    # ../../modules/virtualbox.nix  # VirtualBox guest additions (swap in if using VirtualBox)
  ];

  # ── Unfree packages ──────────────────────────────────────────────────────────
  # Enables proprietary packages across the whole system (system + Home Manager).
  # Required for: Vivaldi, Spotify, Obsidian, corefonts, DaVinci Resolve, etc.
  nixpkgs.config.allowUnfree = true;

  # ── Bootloader ───────────────────────────────────────────────────────────────
  # This VM uses a BIOS/MBR disk (no EFI partition), so systemd-boot cannot be
  # used. GRUB in legacy mode installs to the MBR of /dev/sda instead.
  boot.loader.grub = {
    enable = true;
    device = "/dev/vda";   # VirtIO disk in KVM/QEMU — change to /dev/sda for VirtualBox or bare metal
  };

  # ── Network ──────────────────────────────────────────────────────────────────
  networking.hostName = "nixos";
  # NetworkManager handles connections and integrates with KDE's network applet.
  networking.networkmanager.enable = true;

  # ── Firewall ─────────────────────────────────────────────────────────────────
  networking.firewall.enable = true;
  # Open extra ports as needed:
  # networking.firewall.allowedTCPPorts = [ 8080 3000 ];

  # ── SSH daemon ────────────────────────────────────────────────────────────────
  # Allows you to SSH into the VM from the host machine.
  #   ssh radu@<vm-ip>
  # Find the VM's IP with: ip addr show
  # Or set up a host-only network in virt-manager for a stable address.
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;    # Fine for a local VM
      PermitRootLogin        = "no";    # Never allow root SSH
    };
  };

  # ── Shell: zsh ───────────────────────────────────────────────────────────────
  # This registers zsh as a valid login shell in /etc/shells.
  # The per-user shell is set in the users block below.
  # The actual zsh configuration lives in home/radu.nix.
  programs.zsh.enable = true;

  # ── Users ─────────────────────────────────────────────────────────────────────
  # Passwords are set with `passwd radu` after first boot — never store them here.
  users.users.radu = {
    isNormalUser = true;
    description  = "Radu";
    shell        = pkgs.zsh;
    extraGroups  = [
      "wheel"           # sudo access
      "networkmanager"  # manage Wi-Fi / Ethernet without sudo
      "audio"           # direct ALSA audio access + JACK real-time limits
      "video"           # GPU and display device access
      "input"           # game controller / input device access
      "gamemode"        # allow gamemoderun to grant elevated priority
    ];
  };

  # Lets wheel users run sudo without typing a password.
  # Convenient for a local VM. Set to `true` on real hardware.
  security.sudo.wheelNeedsPassword = false;

  # ── Global packages ───────────────────────────────────────────────────────────
  # Keep this minimal. User-facing tools belong in home/radu.nix where they
  # are tracked per-user and isolated from system changes.
  environment.systemPackages = with pkgs; [
    vim     # Last-resort editor before Home Manager activates
    wget
    curl
    git
    pciutils    # lspci — useful for checking GPU in the VM
    usbutils    # lsusb
  ];

  # ── Nix settings ──────────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    # Deduplicate identical files in the Nix store (hardlinks). Saves disk space.
    auto-optimise-store = true;
    # Allow radu to run `nix` commands (nix shell, nix build, nix develop, etc.)
    trusted-users = [ "root" "radu" ];
    # Binary caches — pre-built packages from the community (avoids compiling)
    substituters = [
      "https://cache.nixos.org"
      "https://nix-community.cachix.org"   # Community packages (home-manager, etc.)
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCUSeBc="
    ];
  };

  # Auto garbage collection — removes unreferenced store paths weekly.
  # Keeps the last 14 days of generations so you can always roll back.
  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 14d";
  };

  # ── State version ─────────────────────────────────────────────────────────────
  # Tracks the NixOS release this system was first set up with.
  # Do NOT change this value after first boot — it guards certain stateful defaults.
  system.stateVersion = "24.11";
}
