# Main system configuration for the "nixos" host.
#
# This file defines host-specific settings and imports all modules.
# The hardware-configuration.nix next to this file is auto-generated by NixOS
# during install — it knows your disk layout, CPU, and kernel modules.
# DO NOT edit hardware-configuration.nix manually.
#
# To apply changes after editing any file here:
#   sudo nixos-rebuild switch --flake /etc/nixos#nixos
#
# To test changes without making them permanent (rolls back on reboot):
#   sudo nixos-rebuild test --flake /etc/nixos#nixos
#
# To roll back to the previous generation if something breaks:
#   sudo nixos-rebuild switch --rollback

{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix  # Auto-generated — leave this file alone
    ../../modules/common.nix
    ../../modules/desktop.nix
    ../../modules/virtualbox.nix
  ];

  # ── Bootloader ──────────────────────────────────────────────────────────────
  # VirtualBox supports both UEFI and BIOS. The NixOS installer sets one up for
  # you — check your hardware-configuration.nix. If it already defines
  # boot.loader.grub.device, remove the two lines below and use GRUB instead.
  #
  # UEFI (modern, default for most VMs):
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  #
  # BIOS / legacy (uncomment these and remove the two lines above if needed):
  # boot.loader.grub.enable = true;
  # boot.loader.grub.device = "/dev/sda";  # adjust to your disk

  # Keep the last 5 boot entries in the systemd-boot menu.
  # Each `nixos-rebuild switch` creates a new entry — this prevents clutter.
  boot.loader.systemd-boot.configurationLimit = 5;

  # ── Kernel ──────────────────────────────────────────────────────────────────
  # The LTS kernel is a safe, stable choice for a VM.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ── Network ─────────────────────────────────────────────────────────────────
  networking.hostName = "nixos";
  # NetworkManager handles connections and integrates with KDE's network applet.
  networking.networkmanager.enable = true;

  # ── Firewall ─────────────────────────────────────────────────────────────────
  # Enabled by default on NixOS. Open specific ports as needed, e.g.:
  # networking.firewall.allowedTCPPorts = [ 8080 ];
  networking.firewall.enable = true;

  # ── Users ────────────────────────────────────────────────────────────────────
  # NixOS manages users declaratively. Passwords are set with `passwd` after
  # first boot — they are NOT stored in this config file.
  users.users.radu = {
    isNormalUser = true;
    description  = "Radu";
    # wheel        → sudo access
    # networkmanager → manage Wi-Fi/Ethernet via KDE applet
    # vboxsf       → read/write VirtualBox shared folders
    extraGroups  = [ "wheel" "networkmanager" "vboxsf" ];
    shell        = pkgs.bash;
  };

  # Lets wheel users run sudo without typing a password.
  # Very convenient while learning — consider setting this to `true` on real hardware.
  security.sudo.wheelNeedsPassword = false;

  # ── Global packages ──────────────────────────────────────────────────────────
  # Keep this section small. Prefer home/radu.nix for user-facing tools —
  # that way your personal setup is tracked separately from system-wide config.
  environment.systemPackages = with pkgs; [
    vim   # Baseline editor available even before Home Manager activates
    wget
    curl
    git
  ];

  # ── Nix settings ─────────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    # Deduplicate identical files in the Nix store — saves disk space.
    auto-optimise-store = true;
    # Allow regular users to run `nix` commands (nix shell, nix build, etc.)
    trusted-users = [ "root" "radu" ];
  };

  # Auto garbage collection — removes old generations weekly.
  # You can always roll back within the 14-day window.
  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 14d";
  };

  # ── State version ────────────────────────────────────────────────────────────
  # Tracks the NixOS release this system was first set up with.
  # Do NOT change this value — it protects certain stateful defaults.
  system.stateVersion = "24.11";
}
